name = "icma-orchestrator"
main = "src/index.ts"
compatibility_date = "2025-01-01"

compatibility_flags = ["nodejs_compat"]

# This serves agents.json from /assets
[assets]
directory = "./assets"
binding = "ASSETS"
