name = "icma-proxy"
main = "src/index.ts"
compatibility_date = "2024-11-06"
workers_dev = true

[[services]]
binding = "WALLET"
service = "wallet-agent"

[[services]]
binding = "REPORT"
service = "report-agent-worker"
